# -*- coding: utf-8 -*-
"""bone fracture detction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1smRNklQ7QnJsI9rLTbOKzmjCYnBzQxgH

#1- INSTALL DEPENDENCIES
"""

!pip install ultralytics kaggle -q

"""# 2-KAGGLE AUTHENTICATION"""

from google.colab import files
files.upload()

"""#3-DOWNLOAD DATASETS

"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d shyamgupta196/fracatlas
!kaggle datasets download -d pkdarabi/bone-fracture-detection-computer-vision-project

"""#4-UNZIP DATASETS"""

!unzip -q fracatlas.zip -d fracatlas_data
!unzip -q bone-fracture-detection-computer-vision-project.zip -d bone_fracture_data

!ls fracatlas_data

"""#5-CONVERT FRACATLAS TO YOLO FORMAT"""

import os, shutil, glob

SRC = "/content/fracatlas_data/FracAtlas"
DST = "/content/fracatlas_yolo"

for split in ["train","val","test"]:
    os.makedirs(f"{DST}/images/{split}", exist_ok=True)
    os.makedirs(f"{DST}/labels/{split}", exist_ok=True)

    for f in glob.glob(f"{SRC}/{split}/img/*"):
        shutil.copy(f, f"{DST}/images/{split}")

    for f in glob.glob(f"{SRC}/{split}/ann/*"):
        shutil.copy(f, f"{DST}/labels/{split}")

"""#6- MERGE BONE FRACTURE DATASETS"""

import os, shutil, glob, json

sources = [
    {
        "path": "/content/fracatlas_yolo",
        "img_map": {"train":"images/train","val":"images/val","test":"images/test"},
        "lbl_map": {"train":"labels/train","val":"labels/val","test":"labels/test"},
        "label_ext": ".json"
    },
    {
        "path": "/content/bone_fracture_data/bone fracture detection.v4-v4.yolov8",
        "img_map": {"train":"train/images","val":"valid/images","test":"test/images"},
        "lbl_map": {"train":"train/labels","val":"valid/labels","test":"test/labels"},
        "label_ext": ".txt"
    },
    {
        "path": "/content/bone_fracture_data/BoneFractureYolo8",
        "img_map": {"train":"train/images","val":"valid/images","test":"test/images"},
        "lbl_map": {"train":"train/labels","val":"valid/labels","test":"test/labels"},
        "label_ext": ".txt"
    }
]

DEST = "/content/combined_bone"
counter = 0

for split in ["train","val","test"]:
    os.makedirs(f"{DEST}/images/{split}", exist_ok=True)
    os.makedirs(f"{DEST}/labels/{split}", exist_ok=True)

for src in sources:
    for split in ["train","val","test"]:
        img_dir = os.path.join(src["path"], src["img_map"][split])
        lbl_dir = os.path.join(src["path"], src["lbl_map"][split])

        for img_path in glob.glob(img_dir+"/*"):
            base = os.path.splitext(os.path.basename(img_path))[0]
            ext  = os.path.splitext(img_path)[1]

            label_path = os.path.join(lbl_dir, base + src["label_ext"])
            yolo_lines = []

            if os.path.exists(label_path):
                if src["label_ext"] == ".json":
                    with open(label_path) as f:
                        data = json.load(f)
                    w,h = data["image_width"], data["image_height"]

                    for ann in data["annotations"]:
                        x1,y1,x2,y2 = ann["box_2d"]
                        xc = (x1+x2)/(2*w)
                        yc = (y1+y2)/(2*h)
                        bw = (x2-x1)/w
                        bh = (y2-y1)/h
                        yolo_lines.append(f"0 {xc:.6f} {yc:.6f} {bw:.6f} {bh:.6f}")
                else:
                    with open(label_path) as f:
                        for l in f:
                            p=l.split()
                            yolo_lines.append(f"0 {' '.join(p[1:])}")

            if not yolo_lines:
                continue

            shutil.copy(img_path, f"{DEST}/images/{split}/{counter}{ext}")
            with open(f"{DEST}/labels/{split}/{counter}.txt","w") as f:
                f.write("\n".join(yolo_lines))
            counter+=1

print("✅ Merge completed")

"""# 7- CREATE YAML FILE FOR YOLO"""

yaml = """
path: /content/combined_bone
train: images/train
val: images/val
test: images/test

names:
  0: fracture
"""
open("/content/combined.yaml","w").write(yaml)
print("✅ YAML created")

!ls /content/combined_bone/images/train | wc -l
!ls /content/combined_bone/labels/train | wc -l
!head /content/combined_bone/labels/train/0.txt

"""#8- TRAIN BONE FRACTURE DETECTION"""

from ultralytics import YOLO

model = YOLO("yolov8n.pt")

result = model.train(
    data="/content/combined.yaml",
    epochs=50,
    imgsz=640,
    batch=16,
    name="bone_fracture_yolov8"
)

"""#9- GRADIO INTERFACE"""

!pip install gradio -q

from ultralytics import YOLO

MODEL_PATH = "/content/runs/detect/bone_fracture_yolov8/weights/best.pt"
model = YOLO(MODEL_PATH)

import cv2
import numpy as np

def detect_fracture(image, conf_threshold):
    # Convert PIL image to OpenCV
    img = np.array(image)
    img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)

    results = model.predict(
        source=img,
        conf=conf_threshold,
        imgsz=640
    )

    annotated_img = results[0].plot()
    annotated_img = cv2.cvtColor(annotated_img, cv2.COLOR_BGR2RGB)

    return annotated_img

import gradio as gr

interface = gr.Interface(
    fn=detect_fracture,
    inputs=[
        gr.Image(type="pil", label="Upload X-ray Image"),
        gr.Slider(0.1, 0.9, value=0.25, step=0.05, label="Confidence Threshold")
    ],
    outputs=gr.Image(type="numpy", label="Detected Fractures"),
    title="🦴 Bone Fracture Detection (YOLOv8)",
    description=(
        "Upload an X-ray image and the model will detect bone fractures "
        "using a trained YOLOv8 model."
    ),
    allow_flagging="never"
)

interface.launch(share=True)